kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-brandon
  namespace: ns-brandon
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: TestKey
      valueFrom:
        secretKeyRef:
          name: envkeys
          key: TestKey 
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true  
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-provider" 
        nodePublishSecretRef:
          name: akv-creds  