name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bcglabacr01.azurecr.io/brandon-courseassessment:latest
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: bcglabacr01
        # Container registry password
        password: vQign8/X5HO3XhfXFWFW05CtHqpYV+dM
        # Container registry server url
        login-server: bcglabacr01.azurecr.io
        
    - name: Push Image to ACR
      run: docker push bcglabacr01.azurecr.io/brandon-courseassessment:latest
    
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1

    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login bcglabacr01.azurecr.io --username bcglabacr01 --password vQign8/X5HO3XhfXFWFW05CtHqpYV+dM

    - name: Package the helm chart
      run: helm package ./helm/brandon-courseassessment

    - name: save helm chart to local registry
      run: |
       helm chart save ./brandon-courseassessment-0.0.1.tgz bcglabacr01.azurecr.io/brandon-courseassessment:latest

    - name: Helm chart Push
      run: helm chart push bcglabacr01.azurecr.io/brandon-courseassessment:latest
